apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: namespace1   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: user1@email.com   # replace with the email of the user
  resourceQuotaSpec:
   hard:
     cpu: "6"
     memory: "16Gi"
     requests.nvidia.com/gpu: "1"
     persistentvolumeclaims: "10" #추후 강의를 위해 10개로 수정하였습니다. 
     requests.storage: "100Gi" #추후 강의를 위해 100Gi로 수정하였습니다. 
     
